"""OpenAI Chat and Anthropic Messages runtime inspired by Pi AI."""

from backend.llm.abort import AbortSignal
from backend.llm.client import LLMClient
from backend.llm.connectivity import ModelConnectivityTester
from backend.llm.context import (
    build_provider_context_payload,
    estimate_messages_tokens,
    estimate_provider_message_tokens,
    estimate_provider_request_tokens,
    estimate_tokens,
)
from backend.llm.contracts import (
    AssistantContent,
    AssistantInputMessage,
    AssistantMessage,
    ChatMessage,
    ChatResponse,
    LLMChatMessage,
    LLMChatResponse,
    LLMToolCall,
    LLMToolDefinition,
    ModelCatalogItem,
    ModelProtocol,
    ProviderJsonObject,
    ProviderJsonValue,
    StopReason,
    SystemMessage,
    TextContent,
    ThinkingContent,
    ToolCall,
    ToolCallContent,
    ToolDefinition,
    ToolResultMessage,
    Usage,
    UserMessage,
    assistant_input_from_message,
    chat_response_from_assistant,
    normalize_chat_response,
)
from backend.llm.errors import (
    LLMConfigurationError,
    LLMErrorCode,
    LLMIntegrationError,
    is_error_retryable,
    is_error_retryable_unshown,
)
from backend.llm.events import (
    AssistantMessageEventStream,
    Completed,
    Failed,
    LLMEvent,
    LLMStreamClosedError,
    ReasoningDelta,
    ReasoningEnded,
    ReasoningStarted,
    StreamStarted,
    TextDelta,
    TextEnded,
    TextStarted,
    ToolCallDelta,
    ToolCallEnded,
    ToolCallStarted,
)
from backend.llm.ports import LLMClientPort, ModelConnectivityTesterPort
from backend.llm.provider_config import (
    ModelAuthMode,
    ModelProviderConfig,
    OpenAICompatibilityOverrides,
    OpenAIMaxTokensField,
)
from backend.llm.registry import ProviderRegistry, default_provider_registry
from backend.llm.retry import RetryPolicy
from backend.llm.thinking import (
    THINKING_EFFORTS,
    ThinkingEffort,
    coerce_thinking_effort,
    normalize_thinking_efforts,
    thinking_budget_tokens,
)

__all__ = [
    "AbortSignal",
    "AssistantContent",
    "AssistantInputMessage",
    "AssistantMessage",
    "AssistantMessageEventStream",
    "ChatMessage",
    "ChatResponse",
    "Completed",
    "Failed",
    "LLMChatMessage",
    "LLMChatResponse",
    "LLMClient",
    "LLMClientPort",
    "LLMConfigurationError",
    "LLMErrorCode",
    "LLMEvent",
    "LLMStreamClosedError",
    "LLMIntegrationError",
    "LLMToolCall",
    "LLMToolDefinition",
    "ModelAuthMode",
    "ModelCatalogItem",
    "ModelConnectivityTester",
    "ModelConnectivityTesterPort",
    "ModelProtocol",
    "ModelProviderConfig",
    "OpenAICompatibilityOverrides",
    "OpenAIMaxTokensField",
    "ProviderJsonObject",
    "ProviderJsonValue",
    "ProviderRegistry",
    "ReasoningDelta",
    "ReasoningEnded",
    "ReasoningStarted",
    "RetryPolicy",
    "StopReason",
    "StreamStarted",
    "SystemMessage",
    "TextContent",
    "TextDelta",
    "TextEnded",
    "TextStarted",
    "THINKING_EFFORTS",
    "ThinkingContent",
    "ThinkingEffort",
    "ToolCall",
    "ToolCallContent",
    "ToolCallDelta",
    "ToolCallEnded",
    "ToolCallStarted",
    "ToolDefinition",
    "ToolResultMessage",
    "Usage",
    "UserMessage",
    "assistant_input_from_message",
    "build_provider_context_payload",
    "chat_response_from_assistant",
    "coerce_thinking_effort",
    "default_provider_registry",
    "estimate_messages_tokens",
    "estimate_provider_message_tokens",
    "estimate_provider_request_tokens",
    "estimate_tokens",
    "is_error_retryable",
    "is_error_retryable_unshown",
    "normalize_chat_response",
    "normalize_thinking_efforts",
    "thinking_budget_tokens",
]
